CREATE DATABASE IF NOT EXISTS edukation;
USE edukation;

CREATE TABLE IF NOT EXISTS User(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    password VARBINARY(50) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS pomodoro(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    resume TEXT NOT NULL,
    FOREIGN KEY(userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS cornell(
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    resume TEXT NOT NULL,
    noteClass TEXT NOT NULL,
    FOREIGN KEY(userId) REFERENCES User(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Remove as tabelas antigas, começando pelas dependentes.
DROP TABLE IF EXISTS timeline;
DROP TABLE IF EXISTS module;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS theme;
DROP TABLE IF EXISTS category;
