CREATE DATABASE IF NOT EXISTS Edukation ;

use Edukation;

CREATE TABLE IF NOT EXISTS users(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255)NOT NULL,
    age INT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    tel VARCHAR(255) NOT NULL UNIQUE
    
)

CREATE TABLE IF NOT EXISTS pomodoro(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    studyTime INT NOT NULL,
    timeDescanse INT NOT NULL
)

CREATE TABLE IF NOT EXISTS mindMap(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    ramification VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS feymann(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,

)

CREATE TABLE IF NOT EXISTS interleavedStudy(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    schoolSubject2 VARCHAR(255) NOT NULL,
    timer INT NOT NULL
)

CREATE TABLE IF NOT EXISTS cornell(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL
)