CREATE DATABASE IF NOT EXISTS Edukation ;

use Edukation;

CREATE TABLE IF NOT EXISTS users(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255)NOT NULL,
    dateBirdth DATE NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password varbinary(255) NOT NULL,
    tel VARCHAR(255) NOT NULL UNIQUE

)

CREATE TABLE IF NOT EXISTS pomodoro(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    studyTime INT NOT NULL,
    timeDescanse INT NOT NULL
)

/* controlar exercicios */
CREATE TABLE IF NOT EXISTS flashcards(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_method INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    question VARCHAR(255) NOT NULL,
    answer VARCHAR(255) NOT NULL
)


 CREATE TABLE category(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    categoryName VARCHAR(255) NOT NULL
 );

CREATE TABLE activity(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idCategory INT FOREING KEY REFERENCES category(id),
    schoolSubject VARCHAR(255) NOT NULL,
    content text ,
    

CREATE TABLE IF NOT EXISTS mindMap(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    ramification VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS feymann(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,

)

CREATE TABLE IF NOT EXISTS interleavedStudy(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL,
    schoolSubject2 VARCHAR(255) NOT NULL,
    timer INT NOT NULL
)

CREATE TABLE IF NOT EXISTS cornell(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUser INT FOREING KEY REFERENCES users(id),
    schoolSubject VARCHAR(255) NOT NULL
)